---
- name: Initialize k3s nodes (master + workers)
  hosts: [master, workers]
  become: true

  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted

  tasks:
    - name: Update and upgrade system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      retries: 3
      delay: 10
      tags: [system]

    - name: Install base tools
      ansible.builtin.apt:
        name:
          - git
          - curl
          - wget
          - vim
          - net-tools
          - jq
          - htop
          - ca-certificates
        state: present
      tags: [system]

    - name: Ensure SSH root login allowed (for provisioning)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present
        validate: 'sshd -t -f %s'
      notify: restart sshd
      tags: [ssh]

    - name: Verify external connectivity (ping test)
      ansible.builtin.command: ping -c 2 8.8.8.8
      register: ping_output
      changed_when: false
      ignore_errors: true
      tags: [verify]

    - name: Report ping status
      ansible.builtin.debug:
        msg: "Ping to 8.8.8.8: {{ 'OK' if ping_output.rc == 0 else 'FAILED' }}"
      tags: [verify]

    - name: Verify APT connectivity
      ansible.builtin.apt:
        update_cache: yes
      register: apt_check
      ignore_errors: true
      changed_when: false
      tags: [verify]

    - name: Report APT check
      ansible.builtin.debug:
        msg: "APT cache update {{ 'OK' if apt_check is not failed else 'FAILED' }}"
      tags: [verify]
